project:
  type: website
  output-dir: docs

website:
  title: "ESBS Bioinformatics"
  navbar:
    background: primary
    left: 
    - text: "Home"
      href: index.qmd
    - text: "1A"
      menu:
      - text: "1 - Pre-processing of sequencing reads"
        href: tutorials-1A/tutorial1.qmd
      - text: "2 - Read mapping on a reference genome"
        href: tutorials-1A/tutorial2.qmd
      - text: "3 - De novo assembly"
        href: tutorials-1A/tutorial3.qmd
      - text: "4 - Annotation of a complete prokaryotic genome"
        href: tutorials-1A/tutorial4.qmd
      - text: "5 - Analysis of eukaryotic sequences"
        href: tutorials-1A/tutorial5.qmd
    - text: "2A"
      menu:
      - text: "1 - Pre-processing of sequencing reads"
        href: tutorials-2A/tutorial1.qmd
      - text: "2 - Read mapping on a reference genome"
        href: tutorials-2A/tutorial2.qmd
      - text: "3 - De novo assembly"
        href: tutorials-2A/tutorial3.qmd
      - text: "4 - Annotation of a complete prokaryotic genome"
        href: tutorials-2A/tutorial4.qmd
      - text: "5 - Analysis of eukaryotic sequences"
        href: tutorials-2A/tutorial5.qmd
    - text: "3A"
      menu:
      - text: "2 - Read mapping on a reference genome"
        href: tutorials-3A/tutorial2.qmd
      - text: "3 - De novo assembly"
        href: tutorials-3A/tutorial3.qmd
      - text: "4 - Annotation of a complete prokaryotic genome"
        href: tutorials-3A/tutorial4.qmd
    - text: "Pharma"
      menu:
      - text: "1 - Pre-processing of sequencing reads"
        href: tutorials-pharma/tutorial1.qmd
      - text: "2 - Read mapping on a reference genome"
        href: tutorials-pharma/tutorial2.qmd
      - text: "3 - De novo assembly"
        href: tutorials-pharma/tutorial3.qmd
      - text: "4 - Annotation of a complete prokaryotic genome"
        href: tutorials-pharma/tutorial4.qmd
      - text: "5 - Analysis of eukaryotic sequences"
        href: tutorials-pharma/tutorial5.qmd
    - text: "Help"
      menu:      
      - text: "Galaxy Help"
        href: help/galaxy.qmd
      - text: "CLI Help"
        href: help/cli.qmd
    tools:
    - icon: github
      menu:
        - text: Source Code
          href:  https://github.com/dorinemerlat/bioinformatics-en
        - text: Report a Bug
          href:  https://github.com/dorinemerlat/bioinformatics-en/issues
    - icon: globe  # Use the globe icon for language switcher
      menu:
        - text: "English"
          href: https://dorinemerlat.github.io/bioinformatics-en/
        - text: "French"
          href: https://dorinemerlat.github.io/bioinformatics-fr/
  search: 
    location: navbar
    type: textbox
    keyboard-shortcut: ["?", "H"]
    copy-button: true
  page-footer: "Copyright 2024, Dorine Merlat. Built with Quarto." 

language: 
  search-box-placeholder: Search

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true


